### ISSUE TITLE
Blank page in post editor when line wrapping is off (v1.2.5.3)

### ISSUE THREAD

**Issue by RulerOfThisWorld** [benjaminprojas/wp-editor#10]
Blank page in post editor when line wrapping is off (v1.2.5.3)

**Comment by benjaminprojas** [comment]
@RulerOfThisWorld can you provide me with some screenshots/more info on this issue?

**Comment by RulerOfThisWorld** [comment]
@benjaminprojas Yes, of course :)
WP 4.4.2
Theme Editor and Plugin Editor work perfectly when Line Wrapping is disabled.

![ok](https://cloud.githubusercontent.com/assets/4064732/12984065/c4bcbbc0-d0f4-11e5-81f2-29cc44bd66af.png)
![blank](https://cloud.githubusercontent.com/assets/4064732/12984064/c4b9bc72-d0f4-11e5-852c-aea6fd2bda6f.png)
![line_wrapping](https://cloud.githubusercontent.com/assets/4064732/12984066/c4bfeb10-d0f4-11e5-8195-8e41ada6fb4a.png)

**Comment by benjaminprojas** [comment]
this is resolved with the newest update of codemirror.
