### ISSUE TITLE
how to use the wp-editor ?

### ISSUE THREAD

**Issue by behle** [benjaminprojas/wp-editor#12]
hi benjamin,
i just dont know how to use the web-editor,
i installed it, activated it, it shows up in my dashboard, i find the setting
-- but for example the wp editor doesnt find my acutal theme but shows under editor theme
, themes i dindt install like ambiance, blackboard ....  just want to change minimal things in my theme int the source text and i`m not able to open the 
CodeMirror feature status you show on your http://wpeditor.net/ first page/home
if you have any turorial or proposal please write back,
as said i see the WP Editor Settings, comlpete main, theme editor, plug in editor .. and dont know how to use the editor

regards and thanks,
behle/karsten

**Comment by behle** [comment]
found a tutorial on youtube
 https://www.youtube.com/watch?v=uGpWfvRm0mI
diffrence to my appearance in my dashboard is that there is no installation of any
plugin editon --- see foto
![wp_editor_meins](https://cloud.githubusercontent.com/assets/17165711/12975962/ac5072ea-d0c0-11e5-9487-3930b7bf8f26.jpg)
![wp_editor_gut](https://cloud.githubusercontent.com/assets/17165711/12975963/ac682fca-d0c0-11e5-8cd1-d570bb3b6504.jpg)

see/attachments
but why ? no idea?proposal?

regrads, karsten

**Comment by benjaminprojas** [comment]
@behle the issue is that there is something blocking the plugin editor from appearing.  Are you in a multisite install? 

Sometimes hosting providers will block this feature to prevent the site from going down accidentally.  Can you check with your hosting provider to see if they have blocked it?
