### ISSUE TITLE
So much blank space

### ISSUE THREAD

**Issue by Patch-Moloughney** [benjaminprojas/wp-editor#15]
Hello there, I am using a child theme of wordpress's twenty sixteen theme and I'm having a problem with a lot of blank space to the top and sides of my content.
I am also using beaver builder to edit the site.

![screenshot 1](https://cloud.githubusercontent.com/assets/17877101/13810126/1eb05b88-eb66-11e5-99fb-1346c8d47bca.png)

I removed the side bar and the content (that was aligned to the left) became center aligned, I would like it to take up the whole width of the page. (by page I just mean the white part)

![screenshot 2](https://cloud.githubusercontent.com/assets/17877101/13810261/dc54a342-eb66-11e5-8548-30a9ca468fbf.png)

This image shows the highest point I can insert a row on my page, I would like to insert a row all the way at the top.

So is there any way to remove all the padding and even the page name "about us" so that when I insert a row with Beaver Builder it will touch the top and sides of the page.

Thank you for your time,
Patch :)

**Comment by benjaminprojas** [comment]
Patch,

I am sorry about the issues you are having with your site!  Unfortunately, this most likely has nothing to do with the WP Editor plugin itself.  WP Editor just manipulates the view of the text editor on the post/page editor.  You will need to contact a WordPress web developer who knows Beaver Builder and who can try to assist you with this.  

Thanks!
