### ISSUE TITLE
Text Editor Insert Link Undefined Values

### ISSUE THREAD

**Issue by jarmerson** [benjaminprojas/wp-editor#20]
I've seen a few reports of this bug in your plugin. We have no console errors. 

`<a href="undefined" title="undefined">`

Is there a solution for this that I'm not finding?

WP 4.4.2 
WP Editor 0.5.5

Thank You

**Comment by benjaminprojas** [comment]
@jarmerson No solution yet, it's pegged for a fix in the next release.  Marking this as a duplicate of issue #1.

**Comment by benjaminprojas** [comment]
@jarmerson also, have you tried updating to the latest version of WP Editor?

**Comment by jarmerson** [comment]
I saw a duplicate issue, but it was closed. 

This plugin hasn't shown any updates available from our network admin. I do see the latest release on the WP plugin page - 1.2.5.3 

I will update that now and get back with you. Thank you for your feedback.

**Comment by benjaminprojas** [comment]
@jarmerson Issue #1 is still open, that's the main one for this same issue.  I don't think that updating will fix this specific issue, but the next release should have this fix (1.2.6).

**Comment by emajen** [comment]
I understand. I just realized I have two github accounts. This is my primary. Thanks again.
