### ISSUE TITLE
Wrong URL in README

### ISSUE THREAD

**Issue by denizdogan** [benjaminprojas/wp-editor#33]
The URL https://wpeditor.net/ leads to some sketchy-looking website. Non-https leads to the right website. I don't know why, but the README leads to the https scam site right now.

**Comment by benjaminprojas** [comment]
Thanks for the heads up on that. The site it redirects to is not a scam, bit it is the wrong site for sure. I will try to get that fixed ASAP.

**Comment by benjaminprojas** [comment]
SSL certificate now works correctly.  https://wpeditor.net is live.
