### ISSUE TITLE
Post/page editor indentation settings

### ISSUE THREAD

**Issue by ferriefi** [benjaminprojas/wp-editor#36]
There are a few typos which break the indentation settings.

classes/WPEditorPosts.php:19
'indentWithTabs' => WPEditorSetting::getValue('enable_post_tab_size') == 'tabs' ? true : false,
should be
'indentWithTabs' => WPEditorSetting::getValue('enable_post_tab_characters') == 'tabs' ? true : false,

js/posts-jquery.js:299
indentSize: WPEPosts.indentSize,
should be
indentUnit: WPEPosts.indentUnit,

**Comment by benjaminprojas** [comment]
@ferriefi thanks!  I'll get those fixed.
