### ISSUE TITLE
Unable to Edit Pages or Posts top buttons in editor (<b>old <li> <ol> etc) broken

### ISSUE THREAD

**Issue by theGuruWithin** [benjaminprojas/wp-editor#41]
![add_new_post_ _shop_akosm_ _wordpress_-_2016-05-23_14 27 03](https://cloud.githubusercontent.com/assets/2244686/15485158/88f8f038-20f2-11e6-9a53-ba10cd0603fe.png)

**Comment by benjaminprojas** [comment]
@theGuruWithin can you provide a screenshot of your console when trying to use the buttons?

**Comment by theGuruWithin** [comment]
i use firefox..  please describe how to get what you want in step by step using firefox pls

**Comment by theGuruWithin** [comment]
i think i figured it out....
![add_new_post_ _shop_akosm_ _wordpress_-_2016-05-23_14 33 54](https://cloud.githubusercontent.com/assets/2244686/15485332/73438464-20f3-11e6-9e94-4bf7b320822e.png)

**Comment by theGuruWithin** [comment]
i am getting NS Error Failure.... but how do i screen grab console? cant figure out

**Comment by theGuruWithin** [comment]
NS_ERROR_FAILURE: 

![console-shot](https://cloud.githubusercontent.com/assets/2244686/15485804/3838a126-20f6-11e6-9b42-3cae0476cd50.jpg)

**Comment by theGuruWithin** [comment]
any thoughts?

**Comment by theGuruWithin** [comment]
Ben is there any other info you need from me to continue diagnoses or anything you want me to try?

**Comment by benjaminprojas** [comment]
@theGuruWithin I'm sorry for the delay in responding.  That is definitely an issue with WP Editor.  I am wondering if it is a conflict with FireFox specifically.  What version of Firefox are you running? And which operating system?

**Comment by theGuruWithin** [comment]
Win7 OS
Firefox 46.0.1
I can give you site access should you need to take a look..... or still happy to do anything you suggest to trouble shoot.

**Comment by theGuruWithin** [comment]
Hi Benjamin,

any news? don't mean to be a bother but i really can't imagine working as well w/o WP-Editor it just improves WP experience %1000

in gratitude,
Arthur

**Comment by benjaminprojas** [comment]
Hey Arthur,

I'm sorry I haven't had a chance to work on this yet.  WP Editor is my hobby right now (free, so it doesn't make me money) I will try to work on it by this weekend and get an update out soon after.  Thanks for your patience!  Will you be available this weekend in case I need more information from you?

**Comment by theGuruWithin** [comment]
Benjamin,

i will be available - happy to give you phone num privately if needed 
And i really do understand that this hobby project - as amazing as it is - Is a hobby .. . so please understand my gratitude for your creation of WP Editor ...

and i am a patient person in total support and appreciation of your efforts.  So please take these nudge reminders as what they are - just to keep the thread alive...

A

**Comment by benjaminprojas** [comment]
Sounds good Arthur! I'll be in touch this weekend.

**Comment by theGuruWithin** [comment]
thank you again
I follow you on Twitter 
If you follow me I can leave you DM of phone info etc if you like.
@theGuruWithin

**Comment by benjaminprojas** [comment]
@theGuruWithin working on it now.  Will be in touch if I can't resolve it with the info I have.

Thanks!

**Comment by benjaminprojas** [comment]
@theGuruWithin looks like I have a fix for this. I was able to duplicate the issue in FireFox and then was able to resolve it.  I will try to have a fix for this available tonight.  Are you comfortable editing the plugin directly to test if I send you the code to modify?

**Comment by theGuruWithin** [comment]
I would give  a try but i am still newbee with plugin writing ... but working on it...

**Comment by benjaminprojas** [comment]
@theGuruWithin Ok, can you try to update to WP 1.2.6.1 and see if it work now as expected? Thanks!

**Comment by theGuruWithin** [comment]
i just installed and will 1.2.6.1 now will open a tag on selected text but won't close tag when select and try to <li> from menu button.

**Comment by theGuruWithin** [comment]
i just installed and now 1.2.6.1 will open a tag on selected text using <li> button,  but WON'Tt close tag

**Comment by theGuruWithin** [comment]
i just installed and will 1.2.6.1 now will open a tag on selected text but won't close tag when select and when try to "<li>" tag from menu button.

**Comment by theGuruWithin** [comment]
i just installed and will 1.2.6.1 now will open a tag on selected text but won't close tag when select and try to < li > tag from menu button.

**Comment by theGuruWithin** [comment]
thank you again for all your help
