### ISSUE TITLE
Unable to Edit Pages or Posts top buttons in editor (<b>old <li> <ol> etc) 2.6.1 still broken

### ISSUE THREAD

**Issue by theGuruWithin** [benjaminprojas/wp-editor#44]
Only opens front tag and won't close tags like < li > or <strong> etc, when text selected.

**Comment by theGuruWithin** [comment]
Hi Benjamin,
Just checking in on progress since i haven't seen this issue turned back into active bug.... Not pressuring just wondering if it is still in your minds eye.

in gratitude,
A

**Comment by benjaminprojas** [comment]
hey Arthur, yep, still top of the list.  Trying to figure out a time to jump back on.  Busy times around here :)

I'll keep you posted.

**Comment by theGuruWithin** [comment]
thanks ... no pressure really....

**Comment by theGuruWithin** [comment]
Hi Benjamin,

Just checking in - no pressure

**Comment by benjaminprojas** [comment]
hey @theGuruWithin thanks for checking in.  My family has been sick so time has been spent caring for them.  They are on the mend now so I should be able to jump back on this soon.

**Comment by theGuruWithin** [comment]
I will keep their health in my daily meditation....

Love and pranams,
Arthur

**Comment by theGuruWithin** [comment]
BTW i tried to edit using Opera and same issues...

**Comment by benjaminprojas** [comment]
@theGuruWithin I have just released a new version of WP Editor that should fix this issue (1.2.6.2) Can you update and let me know if it works as expected?  Thanks!

**Comment by theGuruWithin** [comment]
Seems to be working great both in Firefox 47 and Opera 38.0.2220.31 
Thank you sooooo much ... hope your family is great!

**Comment by benjaminprojas** [comment]
Glad to hear it! Family is on the mend! Thanks for asking.

**Comment by theGuruWithin** [comment]
thank you for what you do in open-source community... you are very generous 

in gratitude
