### ISSUE TITLE
inserting images is broken via the text view of the regular editor

### ISSUE THREAD

**Issue by Kizzycocoa** [benjaminprojas/wp-editor#45]
As above. I primarily use this plugin to edit my style files, and leave the regular editor as normal for pages. The latest update has broken inserting images in text-view!

I have isolated it to this plugin. It is 100% caused by WP-Editor.

**Comment by benjaminprojas** [comment]
@Kizzycocoa can you tell me what version of WP Editor you are using?  We did resolve an issue regarding inserting an image in text view recently.

**Comment by Kizzycocoa** [comment]
@benjaminprojas I am using Version 1.2.6.1, according to Wordpress. I just checked, and I can confirm this bug is still there, at least for myself. the Wordpress version is 4.5.2!

**Comment by benjaminprojas** [comment]
@Kizzycocoa thanks for getting back with me! What browser are you using?  I just updated WP Editor to try and fix some related issues.  Can you update to 1.2.6.2 and see if that resolves the issue?  Thanks!

**Comment by Kizzycocoa** [comment]
@benjaminprojas I was using Firefox, but now it's all fixed! thank you very much! :+1:

**Comment by benjaminprojas** [comment]
Glad to hear it!
