### ISSUE TITLE
Unable to work after WP-editor installed

### ISSUE THREAD

**Issue by rustychar17** [benjaminprojas/wp-editor#46]
Hi there, I've installed WP-editor in WordPress 4.3.1 version running Enigma Pro theme. After plugin installation and activated, there's only "WP-editor" showing on the left panel. But there's nothing showing under "Appearance" as Theme Editor or Plugin Editor.  The other and the only plugin i'm using is "Polylang".

Is there something I'm not getting? Thanks.

**Comment by benjaminprojas** [comment]
@rustychar17 sorry for the delay.  Are you running on a multisite install?  WP-Editor currently does not support multisite so this may be the issue.
