### ISSUE TITLE
Search problem

### ISSUE THREAD

**Issue by Roman1420** [benjaminprojas/wp-editor#78]
Hello!

on my website located a lot of magazines and books. How to configure search so that when I searching for the book showed just the right book, not the page on which it is located.

example in the photo

I whant that search show only book wich I need
Mabye you can help me.

Thank you!
![2](https://cloud.githubusercontent.com/assets/29100031/26637245/ff01781e-462f-11e7-8e9c-d923f07c73ac.png)
![default](https://cloud.githubusercontent.com/assets/29100031/26637253/0666f890-4630-11e7-9989-aedd2d8f547f.png)

**Comment by benjaminprojas** [comment]
@Roman1420 Unfortunately this is outside the scope of what this plugin does. You will need to look elsewhere for development help.  Thanks, and I hope you get it working!
