### ISSUE TITLE
Plugin maintenance update

### ISSUE THREAD

**Issue by daniel-barrows** [benjaminprojas/wp-editor#90]
WP Editor has not been recently updated, and has therefore been marked as unmaintained on the [WordPress.org website](https://wordpress.org/plugins/wp-editor/) with the warning message [described here](https://developer.wordpress.org/plugins/wordpress-org/alerts-and-warnings/#out-of-date).

I use WP Editor daily on WordPress 4.9.8, and it works fine, so fixing this issue probably only requires updating the README or a similar small tweak in a new commit.

As a sidenote, WordPress [4.9 makes CodeMirror the default](https://make.wordpress.org/core/2017/10/22/code-editing-improvements-in-wordpress-4-9/) WordPress editor for themes, thus duplicating some of WP Editor's functionality. As of 4.9.8, CodeMirror is not used for post editing, so WP Editor is still useful for this feature.

**Comment by benjaminprojas** [comment]
@daniel-barrows unfortunately, I am no longer maintaining WP-Editor as gutenberg will be making its appearance very soon and will completely invalidate this plugin from start to finish. Thanks for your interest though! I appreciate it!
